/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 01:32:34 GMT 2018
 */

package system.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import system.controller.SiteController;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SiteController_ESTest extends SiteController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getResource("R`@I}uBkN.26|O", "");
      assertEquals("/static/html/R`@I}uBkN.26|O/.R`@I}uBkN.26|O", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = system.controller.SiteController.__CLR4_1_214f14fjp8v55ov.lambdaInc((-2490), "system.controller.SiteController", (-2490));
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      system.controller.SiteController.__CLR4_1_214f14fjp8v55ov siteController___CLR4_1_214f14fjp8v55ov0 = new system.controller.SiteController.__CLR4_1_214f14fjp8v55ov();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getFavicon();
      assertEquals("/static/html/ico/favicon.ico", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getFile("/static/html//static/html/index.html//static/html/index.html./static/html/index.html");
      assertEquals("/static/html//static/html//static/html/index.html//static/html/index.html./static/html/index.html.html", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getIndex();
      assertEquals("/static/html/index.html", string0);
  }
}
