@startuml

title __SERVICE's Class Diagram__\n

  package system.controller {
    package system.controller.service {
      class FilesService {
          ~ servletContext : ServletContext
          + replaceServerLocationInJsFiles()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class GameArchiver {
          + archiveFinishedGames()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class GameService {
          {static} + CODE_LENGTH : int
          {static} + NUMBER_OF_TRIES_TO_GENERATE_CODE : int
          - games : LinkedList<Game>
          + set()
          + getAll()
          + addGameFromQuiz()
          + getWithQuiz()
          + get()
          + getByCode()
          + remove()
          + removeByCode()
          - getGameWithActualQuiz()
          - generateGameCode()
          + join()
          + getQuestionsForPlayer()
          + getRealQuestionsForPlayer()
          + startGame()
          + answerQuestion()
          + getFinishedGames()
          + removeFinishedGames()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class PlayerService {
          + getAll()
          + addPlayer()
          + get()
          + removePlayer()
          + getPlayersForIds()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class QuestionGroupService {
          - cachedQuestionGroups : LinkedList<QuestionGroup>
          + updateCached()
          + getAll()
          + getAllWithNumberOfQuestions()
          + getAll()
          + getAllWithNumberOfQuestions()
          + get()
          + add()
          + edit()
          + remove()
          + getNumberOfQuestions()
          + rename()
          + getNumberOfQuestions()
          + getQuestionsFromGroups()
          + getQuestionsFromGroupsFree()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class QuestionService {
          - cachedQuestions : LinkedList<Question>
          + updateCached()
          + getAll()
          + get()
          + add()
          + copy()
          + edit()
          + remove()
          + removeQuestionsFromGroup()
          + getAllWithCatNames()
          + getAllWithCatNamesByTeacher()
          - appendCatNamesToQuestions()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class QuizGroupService {
          - cachedQuizGroups : LinkedList<QuizGroup>
          + updateCached()
          + getAll()
          + get()
          + add()
          + edit()
          + remove()
          + rename()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class QuizPartService {
          - cached : LinkedList<QuizPart>
          + updateCached()
          + getAll()
          + get()
          + add()
          + edit()
          + remove()
          + getAllFromQuiz()
          + copy()
          + getAllWithCatNamesFromQuiz()
          - appendCatNamesToQuizParts()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class QuizService {
          - cachedQuizzes : LinkedList<Quiz>
          + updateCached()
          + getAll()
          + get()
          + appendQuizParts()
          + add()
          + edit()
          + remove()
          + removeQuizzesFromGroup()
          + getAllWithCatNames()
          + getAllWithCatNamesByTeacher()
          - appendCatNamesToQuizzes()
          + copy()
          + generateRealQuestions()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class ResultService {
          - cachedResults : LinkedList<Result>
          + updateCached()
          + getAll()
          + getAllByTeacher()
          + get()
          + add()
          - set()
          + grade()
          - recalculatePoints()
          + edit()
          + remove()
          + archiveGames()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class StartupService {
          + postConstruct()
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      class UserService {
          - cached : LinkedList<User>
          + updateCached()
          + getAll()
          + get()
          + get()
          + getById()
          + isPasswordCorrect()
          + add()
          - doesUserWithUsernameExist()
          + edit()
          + copy()
          + remove()
          + addAdminToDatabase()
      }
    }
  }
  

  GameArchiver o-- GameService : gameService
  GameArchiver o-- ResultService : resultService
  GameService o-- PlayerService : playerService
  GameService o-- QuizService : quizService
  GameService o-- QuestionService : questionService
  GameService o-- QuestionGroupService : questionGroupService
  PlayerService o-- PlayerDao : dao
  QuestionGroupService o-- QuestionGroupDao : dao
  QuestionGroupService o-- QuestionService : questionService
  QuestionService o-- QuestionDao : dao
  QuestionService o-- QuestionGroupService : questionGroupService
  QuizGroupService o-- QuizGroupDao : dao
  QuizGroupService o-- QuizService : quizService
  QuizPartService o-- QuizPartDao : dao
  QuizPartService o-- QuestionGroupService : questionGroupService
  QuizService o-- QuizDao : dao
  QuizService o-- QuizGroupService : quizGroupService
  QuizService o-- QuizPartService : quizPartService
  QuizService o-- QuestionGroupService : questionGroupService
  ResultService o-- ResultDao : dao
  ResultService o-- QuizService : quizService
  ResultService o-- PlayerService : playerService
  ResultService o-- QuestionService : questionService
  StartupService o-- FilesService : filesService
  StartupService o-- UserService : userService
  UserService o-- UserDao : dao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
