@startuml

title __DATABASE's Class Diagram__\n

  package system.controller {
    package system.controller.service {
      package system.controller.service.database {
        interface DatabaseEntry {
            {abstract} + getFieldNames()
            {abstract} + getFields()
            {abstract} + getField()
        }
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      package system.controller.service.database {
        class DatabaseToolkit {
            {static} + CONNECTION_TIMEOUT_MS : int
            {static} + GET_UNAPPROVED_HOSPITATION_PLANS_WITH_HOSPITATIONS_AND_TEACHERS : String
            {static} - connection : Connection
            {static} - hasConnected : boolean
            {static} - failedConnection : boolean
            {static} ~ databaseAddress : String
            {static} + getSettingsFromFile()
            {static} + connect()
            {static} + getStringDataFromDatabase()
            {static} - getStringDataFromDatabaseInternal()
            {static} + addStringDataToDatabase()
            {static} - addStringDataToDatabaseInternal()
            {static} + getDataFromDatabase()
            {static} - waitForConnection()
            {static} - getDataFromDatabaseInternal()
            {static} + addDataToDatabase()
            {static} - addDataToDatabaseInternal()
            {static} + getFieldValuesInDbFormat()
            {static} + removeDataFromDatabase()
            {static} - removeDataFromDatabaseInternal()
            {static} + removeItemWhereStringFieldEqualsValue()
            {static} - removeItemWhereStringFieldEqualsValueInternal()
            {static} + getDeleteFilter()
            {static} + getStringFieldValuesInDbFormat()
            {static} + getFieldNamesInDBFormat()
        }
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      package system.controller.service.database {
        enum FilterBehaviour {
          AND
          OR
        }
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      package system.controller.service.database {
        class IntStringBlobDatabaseEntry {
            - content : HashMap<String, Object>
            + IntStringBlobDatabaseEntry()
            + IntStringBlobDatabaseEntry()
            + getFieldNames()
            + getFields()
            + getField()
        }
      }
    }
  }
  

  package system.controller {
    package system.controller.service {
      package system.controller.service.database {
        class StringDatabaseEntry {
            - content : HashMap<String, String>
            ~ StringDatabaseEntry()
            + StringDatabaseEntry()
            + getFieldNames()
            + getFields()
            + getField()
            + toString()
        }
      }
    }
  }
  

  IntStringBlobDatabaseEntry -up-|> DatabaseEntry
  StringDatabaseEntry -up-|> DatabaseEntry


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
