@startuml

title __CONTROLLER's Class Diagram__\n

  package system.controller {
    class Const_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class QuestionController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - initMocksToAvoidTimeoutsInTheTests()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class QuestionGroupController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - initMocksToAvoidTimeoutsInTheTests()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class QuizController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - initMocksToAvoidTimeoutsInTheTests()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class QuizGroupController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class QuizPartController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - initMocksToAvoidTimeoutsInTheTests()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class ResultController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class SiteController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - resetClasses()
    }
  }
  

  package system.controller {
    class UserController_ESTest_scaffolding {
        + nfr : NonFunctionalRequirementRule
        {static} - defaultProperties : Properties
        - threadStopper : ThreadStopper
        {static} + initEvoSuiteFramework()
        {static} + clearEvoSuiteFramework()
        + initTestCase()
        + doneWithTestCase()
        {static} + setSystemProperties()
        {static} - initializeClasses()
        {static} - initMocksToAvoidTimeoutsInTheTests()
        {static} - resetClasses()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
