/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 03 16:41:56 GMT 2018
 */

package system.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import system.controller.SiteController;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SiteController_ESTest extends SiteController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getFavicon();
      assertEquals("/static/html/ico/favicon.ico", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getFile("/static/html/index.html");
      assertEquals("/static/html//static/html/index.html.html", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getIndex();
      assertEquals("/static/html/index.html", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SiteController siteController0 = new SiteController();
      String string0 = siteController0.getResource("/static/html/ico/favicon.ico", "/static/html//static/html/index.html.html");
      assertEquals("/static/html//static/html/ico/favicon.ico//static/html//static/html/index.html.html./static/html/ico/favicon.ico", string0);
  }
}
