/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 07 15:27:06 GMT 2018
 */

package system.controller.simple_frontend_models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import system.controller.simple_frontend_models.QuestionWithCategoryNames;
import system.model.classes.questions.Question;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QuestionWithCategoryNames_ESTest extends QuestionWithCategoryNames_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      questionWithCategoryNames0.setSubsubcategoryName("c_)wY_M\u0007Q");
      String string0 = questionWithCategoryNames0.getSubsubcategoryName();
      assertEquals("c_)wY_M\u0007Q", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0, "", "", "");
      String string0 = questionWithCategoryNames0.getSubsubcategoryName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      QuestionWithCategoryNames questionWithCategoryNames1 = new QuestionWithCategoryNames(questionWithCategoryNames0, "", "", "");
      String string0 = questionWithCategoryNames1.getSubcategoryName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      QuestionWithCategoryNames questionWithCategoryNames0 = null;
      try {
        questionWithCategoryNames0 = new QuestionWithCategoryNames((Question) null, (String) null, "FRI]/", "system.controller.simple_frontend_models.QuestionWithCategoryNames");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.model.classes.questions.Question", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      QuestionWithCategoryNames questionWithCategoryNames0 = null;
      try {
        questionWithCategoryNames0 = new QuestionWithCategoryNames((Question) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.model.classes.questions.Question", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      String string0 = questionWithCategoryNames0.getSubsubcategoryName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      questionWithCategoryNames0.setCategoryName("c_)wY_M\u0007Q");
      String string0 = questionWithCategoryNames0.getCategoryName();
      assertEquals("c_)wY_M\u0007Q", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      String string0 = questionWithCategoryNames0.getCategoryName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      String string0 = questionWithCategoryNames0.getSubcategoryName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      QuestionWithCategoryNames questionWithCategoryNames1 = new QuestionWithCategoryNames(questionWithCategoryNames0, "", "", "");
      String string0 = questionWithCategoryNames1.getCategoryName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Question question0 = mock(Question.class, new ViolatedAssumptionAnswer());
      QuestionWithCategoryNames questionWithCategoryNames0 = new QuestionWithCategoryNames(question0);
      questionWithCategoryNames0.setSubcategoryName("YZLs3DaL@<m#=Q[8&+Q");
      String string0 = questionWithCategoryNames0.getSubcategoryName();
      assertEquals("YZLs3DaL@<m#=Q[8&+Q", string0);
  }
}
