/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 01:31:11 GMT 2018
 */

package system.model.games;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ListOfQuestions_ESTest extends ListOfQuestions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = ListOfQuestions.__CLR4_1_2ipipjp8v54y0.lambdaInc((-901), "", (-1));
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ListOfQuestions.__CLR4_1_2ipipjp8v54y0 listOfQuestions___CLR4_1_2ipipjp8v54y0_0 = new ListOfQuestions.__CLR4_1_2ipipjp8v54y0();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ListOfQuestions listOfQuestions0 = new ListOfQuestions();
      LinkedList<String> linkedList0 = listOfQuestions0.getQuestionIds();
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ListOfQuestions listOfQuestions0 = new ListOfQuestions();
      listOfQuestions0.setQuestionIds((LinkedList<String>) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ListOfQuestions listOfQuestions0 = new ListOfQuestions((LinkedList<String>) null);
  }
}
