/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 01:22:37 GMT 2018
 */

package system.model.games;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import system.model.questions.Question;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ListOfRealQuestions_ESTest extends ListOfRealQuestions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(1736);
      Object object0 = ListOfRealQuestions.__CLR4_1_2iwiwjp8v54ya.lambdaInc(1650, (Object) integer0, 2157);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ListOfRealQuestions.__CLR4_1_2iwiwjp8v54ya listOfRealQuestions___CLR4_1_2iwiwjp8v54ya0 = new ListOfRealQuestions.__CLR4_1_2iwiwjp8v54ya();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ListOfRealQuestions listOfRealQuestions0 = new ListOfRealQuestions();
      LinkedList<Question> linkedList0 = listOfRealQuestions0.getQuestions();
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ListOfRealQuestions listOfRealQuestions0 = new ListOfRealQuestions();
      listOfRealQuestions0.setQuestions((LinkedList<Question>) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ListOfRealQuestions listOfRealQuestions0 = new ListOfRealQuestions((LinkedList<Question>) null);
  }
}
