/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 01:25:01 GMT 2018
 */

package system.model.games;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Player_ESTest extends Player_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Player.__CLR4_1_2h3h3jp8v54wv player___CLR4_1_2h3h3jp8v54wv0 = new Player.__CLR4_1_2h3h3jp8v54wv();
      Object object0 = Player.__CLR4_1_2h3h3jp8v54wv.lambdaInc(630, (Object) player___CLR4_1_2h3h3jp8v54wv0, (-1765));
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Player player0 = new Player();
      String string0 = player0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Player player0 = new Player();
      player0.setName("CG1~MJ^^KY]i");
      String string0 = player0.getName();
      assertEquals("CG1~MJ^^KY]i", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Player player0 = new Player("");
      player0.setId((String) null);
      String string0 = player0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Player player0 = new Player("", "");
      player0.setName("");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Player player0 = new Player();
      String string0 = player0.getId();
      assertEquals("00000000-0100-4000-8200-000003000000", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Player player0 = new Player("", "");
      String string0 = player0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Player player0 = new Player("", "");
      String string0 = player0.getName();
      assertEquals("", string0);
  }
}
