/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 01:30:18 GMT 2018
 */

package system.controller.simple_frontend_models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import system.controller.simple_frontend_models.QuizPartWithCategoryNames;
import system.model.quizzes.QuizPart;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QuizPartWithCategoryNames_ESTest extends QuizPartWithCategoryNames_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object object0 = QuizPartWithCategoryNames.__CLR4_1_2mamajp8v551i.lambdaInc(0, (Object) "", (-2590));
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      QuizPartWithCategoryNames.__CLR4_1_2mamajp8v551i quizPartWithCategoryNames___CLR4_1_2mamajp8v551i0 = new QuizPartWithCategoryNames.__CLR4_1_2mamajp8v551i();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("k~|yEATaytSZ,2MuF[", "k~|yEATaytSZ,2MuF[", "k~|yEATaytSZ,2MuF[", 363, 816, (String) null, "", "", "system.model.quizzes.QuizPart", ".lfy'O2w!c>^PK,&$", "");
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames1 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames(quizPartWithCategoryNames0, "yphh`xCurs*K,", "system.model.quizzes.QuizPart", (String) null);
      String string0 = quizPartWithCategoryNames1.getSubsubcategoryName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "S/'Aw\"sxpAl", (String) null, 805, 805, "", "", "", "", "", "S/'Aw\"sxpAl");
      String string0 = quizPartWithCategoryNames0.getSubsubcategoryName();
      assertEquals("S/'Aw\"sxpAl", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "", 333, 1946, "", "3<j ctbf7*4~[~_T", (String) null, "", (String) null, (String) null);
      String string0 = quizPartWithCategoryNames0.getSubcategoryName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "", 829, 0, "", "", "", "", "", "system.controller.simple_frontend_models.QuizPartWithCategoryNames");
      String string0 = quizPartWithCategoryNames0.getSubcategoryName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "", (-595), 817, "", "", "system.model.quizzes.QuizPart", (String) null, "", "");
      String string0 = quizPartWithCategoryNames0.getCategoryName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = null;
      try {
        quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames((QuizPart) null, "system.model.quizzes.QuizPart", "system.model.quizzes.QuizPart", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.model.quizzes.QuizPart", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = null;
      try {
        quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames((QuizPart) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.model.quizzes.QuizPart", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "", (-595), 817, "", "", "system.model.quizzes.QuizPart", (String) null, "", "");
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames1 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames(quizPartWithCategoryNames0);
      assertFalse(quizPartWithCategoryNames1.equals((Object)quizPartWithCategoryNames0));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "Nu562pN\"", "", 0, (-2590), "dS5?BNJMrTD1rz", "", "Nu562pN\"", "dS5?BNJMrTD1rz", "dS5?BNJMrTD1rz", "");
      quizPartWithCategoryNames0.setCategoryName("");
      String string0 = quizPartWithCategoryNames0.getCategoryName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "Nu562pN\"", "", 0, (-2590), "dS5?BNJMrTD1rz", "", "Nu562pN\"", "dS5?BNJMrTD1rz", "dS5?BNJMrTD1rz", "");
      quizPartWithCategoryNames0.setSubsubcategoryName("");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "Nu562pN\"", "", 0, (-2590), "dS5?BNJMrTD1rz", "", "Nu562pN\"", "dS5?BNJMrTD1rz", "dS5?BNJMrTD1rz", "");
      String string0 = quizPartWithCategoryNames0.getSubsubcategoryName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("Z[Ow^6A\"7:", "Z[Ow^6A\"7:", (-2879), (-2879), "Z[Ow^6A\"7:", "Z[Ow^6A\"7:", "Z[Ow^6A\"7:", "Z[Ow^6A\"7:", "Z[Ow^6A\"7:", "Z[Ow^6A\"7:");
      quizPartWithCategoryNames0.setSubcategoryName("");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "Nu562pN\"", "", 0, (-2590), "dS5?BNJMrTD1rz", "", "Nu562pN\"", "dS5?BNJMrTD1rz", "dS5?BNJMrTD1rz", "");
      String string0 = quizPartWithCategoryNames0.getCategoryName();
      assertEquals("dS5?BNJMrTD1rz", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      system.controller.simple_frontend_models.QuizPartWithCategoryNames quizPartWithCategoryNames0 = new system.controller.simple_frontend_models.QuizPartWithCategoryNames("", "Nu562pN\"", "", 0, (-2590), "dS5?BNJMrTD1rz", "", "Nu562pN\"", "dS5?BNJMrTD1rz", "dS5?BNJMrTD1rz", "");
      String string0 = quizPartWithCategoryNames0.getSubcategoryName();
      assertEquals("dS5?BNJMrTD1rz", string0);
  }
}
