@startuml

title __SIMPLE_FRONTEND_MODELS's Class Diagram__\n

  package system.controller {
    package system.controller.simple_frontend_models {
      class GameWithActualQuiz_ESTest {
          + test0()
          + test1()
          + test2()
          + test3()
          + test4()
          + test5()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class GameWithActualQuiz_ESTest_scaffolding {
          + nfr : NonFunctionalRequirementRule
          {static} - defaultProperties : Properties
          - threadStopper : ThreadStopper
          {static} + initEvoSuiteFramework()
          {static} + clearEvoSuiteFramework()
          + initTestCase()
          + doneWithTestCase()
          {static} + setSystemProperties()
          {static} - initializeClasses()
          {static} - initMocksToAvoidTimeoutsInTheTests()
          {static} - resetClasses()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuestionGroupWithNumberOfQuestions_ESTest {
          + test0()
          + test1()
          + test2()
          + test3()
          + test4()
          + test5()
          + test6()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuestionGroupWithNumberOfQuestions_ESTest_scaffolding {
          + nfr : NonFunctionalRequirementRule
          {static} - defaultProperties : Properties
          - threadStopper : ThreadStopper
          {static} + initEvoSuiteFramework()
          {static} + clearEvoSuiteFramework()
          + initTestCase()
          + doneWithTestCase()
          {static} + setSystemProperties()
          {static} - initializeClasses()
          {static} - initMocksToAvoidTimeoutsInTheTests()
          {static} - resetClasses()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuestionWithCategoryNames_ESTest {
          + test00()
          + test01()
          + test02()
          + test03()
          + test04()
          + test05()
          + test06()
          + test07()
          + test08()
          + test09()
          + test10()
          + test11()
          + test12()
          + test13()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuestionWithCategoryNames_ESTest_scaffolding {
          + nfr : NonFunctionalRequirementRule
          {static} - defaultProperties : Properties
          - threadStopper : ThreadStopper
          {static} + initEvoSuiteFramework()
          {static} + clearEvoSuiteFramework()
          + initTestCase()
          + doneWithTestCase()
          {static} + setSystemProperties()
          {static} - initializeClasses()
          {static} - initMocksToAvoidTimeoutsInTheTests()
          {static} - resetClasses()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuizPartWithCategoryNames_ESTest {
          + test00()
          + test01()
          + test02()
          + test03()
          + test04()
          + test05()
          + test06()
          + test07()
          + test08()
          + test09()
          + test10()
          + test11()
          + test12()
          + test13()
          + test14()
          + test15()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuizPartWithCategoryNames_ESTest_scaffolding {
          + nfr : NonFunctionalRequirementRule
          {static} - defaultProperties : Properties
          - threadStopper : ThreadStopper
          {static} + initEvoSuiteFramework()
          {static} + clearEvoSuiteFramework()
          + initTestCase()
          + doneWithTestCase()
          {static} + setSystemProperties()
          {static} - initializeClasses()
          {static} - resetClasses()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuizWithCategoryNames_ESTest {
          + test00()
          + test01()
          + test02()
          + test03()
          + test04()
          + test05()
          + test06()
          + test07()
          + test08()
          + test09()
          + test10()
          + test11()
          + test12()
          + test13()
          + test14()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class QuizWithCategoryNames_ESTest_scaffolding {
          + nfr : NonFunctionalRequirementRule
          {static} - defaultProperties : Properties
          - threadStopper : ThreadStopper
          {static} + initEvoSuiteFramework()
          {static} + clearEvoSuiteFramework()
          + initTestCase()
          + doneWithTestCase()
          {static} + setSystemProperties()
          {static} - initializeClasses()
          {static} - initMocksToAvoidTimeoutsInTheTests()
          {static} - resetClasses()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class Response_ESTest {
          + test0()
          + test1()
          + test2()
          + test3()
          + test4()
          + test5()
          + test6()
      }
    }
  }
  

  package system.controller {
    package system.controller.simple_frontend_models {
      class Response_ESTest_scaffolding {
          + nfr : NonFunctionalRequirementRule
          {static} - defaultProperties : Properties
          - threadStopper : ThreadStopper
          {static} + initEvoSuiteFramework()
          {static} + clearEvoSuiteFramework()
          + initTestCase()
          + doneWithTestCase()
          {static} + setSystemProperties()
          {static} - initializeClasses()
          {static} - resetClasses()
      }
    }
  }
  

  GameWithActualQuiz_ESTest -up-|> GameWithActualQuiz_ESTest_scaffolding
  QuestionGroupWithNumberOfQuestions_ESTest -up-|> QuestionGroupWithNumberOfQuestions_ESTest_scaffolding
  QuestionWithCategoryNames_ESTest -up-|> QuestionWithCategoryNames_ESTest_scaffolding
  QuizPartWithCategoryNames_ESTest -up-|> QuizPartWithCategoryNames_ESTest_scaffolding
  QuizWithCategoryNames_ESTest -up-|> QuizWithCategoryNames_ESTest_scaffolding
  Response_ESTest -up-|> Response_ESTest_scaffolding


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
