/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 07 15:34:30 GMT 2018
 */

package system.controller.service.database;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import system.controller.service.database.MySQLDatabaseService;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MySQLDatabaseService_ESTest extends MySQLDatabaseService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MySQLDatabaseService mySQLDatabaseService0 = new MySQLDatabaseService();
      // Undeclared exception!
      try { 
        Injector.executePostConstruct((Object) mySQLDatabaseService0, (Class<?>) MySQLDatabaseService.class);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to execute @PostConstructor in system.controller.service.database.MySQLDatabaseService
         //
         verifyException("org.evosuite.runtime.javaee.injection.Injector", e);
      }
  }
}
