/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 07 15:29:01 GMT 2018
 */

package system.model.classes.games;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import system.model.classes.games.FreeTextAnswer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FreeTextAnswer_ESTest extends FreeTextAnswer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("");
      Double double0 = new Double(2080.865524077);
      freeTextAnswer0.setCorrect(double0);
      Double double1 = freeTextAnswer0.getCorrect();
      assertEquals(2080.865524077, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("system.model.classes.games.FreeTextAnswer");
      Double double0 = new Double(2710.36230097667);
      freeTextAnswer0.setCorrect(double0);
      Double double1 = freeTextAnswer0.getCorrect();
      assertEquals(2710.36230097667, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Double double0 = new Double(5070.3);
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer((String) null, double0);
      String string0 = freeTextAnswer0.getAnswer();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("qo)t#fnkW");
      String string0 = freeTextAnswer0.getAnswer();
      assertEquals("qo)t#fnkW", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("system.model.classes.games.FreeTextAnswer");
      Double double0 = new Double(0.0);
      freeTextAnswer0.setCorrect(double0);
      Double double1 = freeTextAnswer0.getCorrect();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("system.model.classes.games.FreeTextAnswer");
      Double double0 = freeTextAnswer0.getCorrect();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("");
      String string0 = freeTextAnswer0.getAnswer();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("system.model.classes.games.FreeTextAnswer");
      freeTextAnswer0.setAnswer("system.model.classes.games.FreeTextAnswer");
      assertNull(freeTextAnswer0.getCorrect());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Double double0 = new Double((-1.0));
      FreeTextAnswer freeTextAnswer0 = new FreeTextAnswer("", double0);
      Double double1 = freeTextAnswer0.getCorrect();
      assertEquals((-1.0), (double)double1, 0.01);
  }
}
