/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 12:26:32 GMT 2018
 */

package system.controller.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import system.controller.dao.QuizGroupDao;
import system.controller.service.QuizGroupService;
import system.controller.service.QuizService;
import system.model.quizzes.QuizGroup;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QuizGroupService_ESTest extends QuizGroupService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object object0 = QuizGroupService.__CLR4_1_21e11e1jp8v55xe.lambdaInc(0, "OaYZ!O=", 0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      QuizGroupService.__CLR4_1_21e11e1jp8v55xe quizGroupService___CLR4_1_21e11e1jp8v55xe0 = new QuizGroupService.__CLR4_1_21e11e1jp8v55xe();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      LinkedList<QuizGroup> linkedList0 = quizGroupService0.getAll();
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      QuizGroup quizGroup0 = mock(QuizGroup.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(quizGroup0).getId();
      quizGroupService0.add(quizGroup0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList<QuizGroup>) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      QuizGroup quizGroup0 = mock(QuizGroup.class, new ViolatedAssumptionAnswer());
      doReturn("").when(quizGroup0).getId();
      quizGroupService0.add(quizGroup0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      doReturn((String) null).when(quizGroupDao0).remove(anyString());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      system.controller.service.QuizGroupService quizGroupService1 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao1 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService1, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao1);
      QuizService quizService1 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService1, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService1);
      Injector.validateBean(quizGroupService1, (Class<?>) system.controller.service.QuizGroupService.class);
      quizGroupService0.quizService = quizGroupService1.quizService;
      quizGroupService0.quizService = null;
      // Undeclared exception!
      try { 
        quizGroupService0.remove("system.controller.service.QuizGroupService");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.QuizGroupService", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      quizGroupService0.dao = null;
      // Undeclared exception!
      try { 
        quizGroupService0.getAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.QuizGroupService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      system.controller.service.QuizGroupService quizGroupService1 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao1 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao1).getAll();
      Injector.inject(quizGroupService1, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao1);
      QuizService quizService1 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService1, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService1);
      Injector.validateBean(quizGroupService1, (Class<?>) system.controller.service.QuizGroupService.class);
      QuizGroupDao quizGroupDao2 = quizGroupService1.dao;
      quizGroupService0.dao = quizGroupDao2;
      // Undeclared exception!
      try { 
        quizGroupService0.get("Ym1KW*'Z&(  }F`JO<");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.QuizGroupService", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      // Undeclared exception!
      try { 
        quizGroupService0.add((QuizGroup) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.QuizGroupService", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList<QuizGroup>) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      QuizGroup quizGroup0 = mock(QuizGroup.class, new ViolatedAssumptionAnswer());
      doReturn("ok").when(quizGroup0).getId();
      quizGroupService0.add(quizGroup0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      quizGroupService0.updateCached();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      doReturn((String) null).when(quizGroupDao0).remove(anyString());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      String string0 = quizGroupService0.remove("system.controller.service.QuizGroupService");
      assertEquals("ok", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null, (LinkedList) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      // Undeclared exception!
      try { 
        quizGroupService0.rename("", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.QuizGroupService", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      system.controller.service.QuizGroupService quizGroupService0 = new system.controller.service.QuizGroupService();
      QuizGroupDao quizGroupDao0 = mock(QuizGroupDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(quizGroupDao0).getAll();
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "dao", (Object) quizGroupDao0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class, "quizService", (Object) quizService0);
      Injector.validateBean(quizGroupService0, (Class<?>) system.controller.service.QuizGroupService.class);
      // Undeclared exception!
      try { 
        quizGroupService0.get("Ym1KW*'Z&(  }F`JO<");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.QuizGroupService", e);
      }
  }
}
