/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 03 15:45:30 GMT 2018
 */

package system.controller.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import system.controller.dao.PlayerDao;
import system.controller.service.PlayerService;
import system.model.games.Player;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlayerService_ESTest extends PlayerService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlayerService playerService0 = new PlayerService();
      PlayerDao playerDao0 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(playerDao0).getPlayers();
      Injector.inject(playerService0, (Class<?>) PlayerService.class, "dao", (Object) playerDao0);
      Injector.validateBean(playerService0, (Class<?>) PlayerService.class);
      // Undeclared exception!
      try { 
        playerService0.addPlayer((Player) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.PlayerService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlayerService playerService0 = new PlayerService();
      PlayerDao playerDao0 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(playerDao0).getPlayers();
      Injector.inject(playerService0, (Class<?>) PlayerService.class, "dao", (Object) playerDao0);
      Injector.validateBean(playerService0, (Class<?>) PlayerService.class);
      LinkedList<Player> linkedList0 = playerService0.getAll();
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlayerService playerService0 = new PlayerService();
      PlayerDao playerDao0 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(playerDao0).getPlayers();
      Injector.inject(playerService0, (Class<?>) PlayerService.class, "dao", (Object) playerDao0);
      Injector.validateBean(playerService0, (Class<?>) PlayerService.class);
      // Undeclared exception!
      try { 
        playerService0.removePlayer("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.PlayerService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlayerService playerService0 = new PlayerService();
      PlayerDao playerDao0 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(playerDao0).getPlayers();
      Injector.inject(playerService0, (Class<?>) PlayerService.class, "dao", (Object) playerDao0);
      Injector.validateBean(playerService0, (Class<?>) PlayerService.class);
      // Undeclared exception!
      try { 
        playerService0.get("PWj~nG");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.PlayerService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlayerService playerService0 = new PlayerService();
      PlayerDao playerDao0 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      Injector.inject(playerService0, (Class<?>) PlayerService.class, "dao", (Object) playerDao0);
      Injector.validateBean(playerService0, (Class<?>) PlayerService.class);
      playerService0.dao = null;
      PlayerService playerService1 = new PlayerService();
      PlayerDao playerDao1 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(playerDao1).getPlayers();
      Injector.inject(playerService1, (Class<?>) PlayerService.class, "dao", (Object) playerDao1);
      Injector.validateBean(playerService1, (Class<?>) PlayerService.class);
      // Undeclared exception!
      try { 
        playerService1.get((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.PlayerService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlayerService playerService0 = new PlayerService();
      PlayerDao playerDao0 = mock(PlayerDao.class, new ViolatedAssumptionAnswer());
      Injector.inject(playerService0, (Class<?>) PlayerService.class, "dao", (Object) playerDao0);
      Injector.validateBean(playerService0, (Class<?>) PlayerService.class);
      // Undeclared exception!
      try { 
        playerService0.getPlayersForIds((LinkedList<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.PlayerService", e);
      }
  }
}
