/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 07 14:50:46 GMT 2018
 */

package system.controller.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import system.controller.service.PlayerService;
import system.controller.service.QuestionService;
import system.controller.service.QuizService;
import system.controller.service.ResultService;
import system.model.classes.Result;
import system.model.classes.games.Game;
import system.model.dao.ResultDao;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResultService_ESTest extends ResultService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      Double double0 = new Double((-2343));
      // Undeclared exception!
      try { 
        resultService0.grade("B7*tFM};o7hE+XB3*f", (-2343), "system.controller.service.QuestionService", double0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.ResultService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      QuizService quizService1 = resultService0.quizService;
      resultService0.quizService = quizService1;
      QuizService quizService2 = resultService0.quizService;
      resultService0.quizService = quizService2;
      // Undeclared exception!
      try { 
        resultService0.get("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.ResultService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      // Undeclared exception!
      try { 
        resultService0.add((Result) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.ResultService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      LinkedList<Result> linkedList0 = resultService0.getAll();
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null, (LinkedList) null).when(resultDao0).getAll();
      doReturn((String) null).when(resultDao0).remove(anyString());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Result result0 = mock(Result.class, new ViolatedAssumptionAnswer());
      doReturn((String) null, (String) null).when(result0).getId();
      resultService0.edit(result0);
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      Result result0 = mock(Result.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(result0).getId();
      resultService0.add(result0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      // Undeclared exception!
      try { 
        resultService0.archiveGames((LinkedList<Game>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.ResultService", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      resultService0.updateCached();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      doReturn((String) null).when(resultDao0).remove(anyString());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      String string0 = resultService0.remove("J7L=");
      assertEquals("ok", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = mock(ResultDao.class, new ViolatedAssumptionAnswer());
      doReturn((LinkedList) null).when(resultDao0).getAll();
      Injector.inject(resultService0, (Class<?>) ResultService.class, "dao", (Object) resultDao0);
      PlayerService playerService0 = mock(PlayerService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "playerService", (Object) playerService0);
      QuestionService questionService0 = mock(QuestionService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "questionService", (Object) questionService0);
      QuizService quizService0 = mock(QuizService.class, new ViolatedAssumptionAnswer());
      Injector.inject(resultService0, (Class<?>) ResultService.class, "quizService", (Object) quizService0);
      Injector.validateBean(resultService0, (Class<?>) ResultService.class);
      // Undeclared exception!
      try { 
        resultService0.getAllByTeacher("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.service.ResultService", e);
      }
  }
}
